import { PLAYER_EFFECT_BUFF_REGISTRY } from '../../shared/player_effect_buff_registry';

export const SHAMAN_BUFF_REGISTRY = {
  ...PLAYER_EFFECT_BUFF_REGISTRY,
  maelstrom_weapon: { iconName: 'spell_nature_unrelentingstorm', emoji: '⚡', displayName: 'Maelstrom Weapon' },
  doom_winds: { iconName: 'ability_ironmaidens_swirlingvortex', emoji: '🌪️', displayName: 'Doom Winds' },
  ascendance: { iconName: 'spell_fire_elementaldevastation', emoji: '⬆️', displayName: 'Ascendance' },
  surging_totem: { iconName: 'inv_ability_totemicshaman_surgingtotem', emoji: '🗿', displayName: 'Surging Totem' },
  crash_lightning: { iconName: 'spell_shaman_crashlightning', emoji: '⚡', displayName: 'Crash Lightning' },
  converging_storms: { iconName: 'spell_shaman_stormblast', emoji: '🌩️', displayName: 'Converging Storms' },
  storm_unleashed: { iconName: 'inv12_apextalent_shaman_stormunleashed', emoji: '🌩️', displayName: 'Storm Unleashed' },
  flurry: { iconName: 'ability_shaman_flurry', emoji: '💨', displayName: 'Flurry' },
  lively_totems: { iconName: 'spell_fire_searingtotem', emoji: '🔥', displayName: 'Lively Totems' },
  searing_totem: { iconName: 'spell_fire_searingtotem', emoji: '🔥', displayName: 'Searing Totem', hideTimer: true },
  tempest: { iconName: 'inv_ability_stormcallershaman_tempest', emoji: '⛈️', displayName: 'Tempest' },
  stormsurge: { iconName: 'ability_shaman_maelstromweapon', emoji: '⚡', displayName: 'Stormsurge' },
  stormblast: { iconName: 'spell_shaman_stormblast', emoji: '🌩️', displayName: 'Stormblast' },
  surging_elements: { iconName: 'spell_nature_elementalprecision_1', emoji: '⚡', displayName: 'Surging Elements' },
  hot_hand: { iconName: 'spell_fire_playingwithfire', emoji: '🔥', displayName: 'Hot Hand' },
  raging_maelstrom: { iconName: 'inv_magic_swirl_color3', emoji: '⚡', displayName: 'Raging Maelstrom' },
  lightning_strikes: { iconName: 'spell_shaman_thorimsinvocation', emoji: '⚡', displayName: 'Lightning Strikes' },
  forceful_winds: { iconName: 'ability_shaman_windwalktotem', emoji: '💨', displayName: 'Forceful Winds' },
  lightning_shield: { iconName: 'spell_nature_lightningshield', emoji: '⚡', displayName: 'Lightning Shield', hideTimer: true },
  flametongue_weapon: { iconName: 'spell_fire_flametounge', emoji: '🔥', displayName: 'Flametongue Weapon' },
  windfury_weapon: { iconName: 'spell_nature_cyclone', emoji: '🌪️', displayName: 'Windfury Weapon', hideTimer: true },
  flame_shock: { iconName: 'spell_fire_flameshock', emoji: '🔥', displayName: 'Flame Shock' },
  lashing_flames: { iconName: 'spell_fire_lavaspawn', emoji: '🔥', displayName: 'Lashing Flames' },
  feral_spirit: { iconName: 'spell_shaman_feralspirit', emoji: '🐺', displayName: 'Feral Spirit' },
  primordial_storm: { iconName: 'ability_shaman_ascendance', emoji: '🌩️', displayName: 'Primordial Storm' },
  static_accumulation: { iconName: 'spell_nature_lightningoverload', emoji: '⚡', displayName: 'Static Accumulation' },
  earthen_weapon: { iconName: 'spell_nature_strengthofearthtotem02', emoji: '🪨', displayName: 'Earthen Weapon' },
  molten_weapon: { iconName: 'spell_fire_elemental_totem', emoji: '🔥', displayName: 'Molten Weapon' },
  icy_edge: { iconName: 'spell_frost_frostshock', emoji: '❄️', displayName: 'Icy Edge' },
  crackling_surge: { iconName: 'spell_beastmaster_wolf', emoji: '⚡', displayName: 'Crackling Surge' },
  amplification_core: { iconName: 'spell_holy_powerinfusion', emoji: '📡', displayName: 'Amplification Core' },
  whirling_air: { iconName: 'inv_10_elementalcombinedfoozles_air', emoji: '💨', displayName: 'Whirling Air' },
  whirling_fire: { iconName: 'inv_10_elementalcombinedfoozles_fire', emoji: '🔥', displayName: 'Whirling Fire' },
  whirling_earth: { iconName: 'inv_10_elementalcombinedfoozles_earth', emoji: '🪨', displayName: 'Whirling Earth' },
  elemental_overflow: { iconName: 'spell_shaman_lavasurge', emoji: '🌋', displayName: 'Elemental Overflow' },
  totemic_rebound: { iconName: 'spell_nature_windfury', emoji: '🔁', displayName: 'Totemic Rebound' },
  winning_streak: { iconName: 'ability_shaman_stormstrike', emoji: '🏆', displayName: 'Winning Streak!' },
  electrostatic_wager: { iconName: 'spell_nature_lightningoverload', emoji: '🎲', displayName: 'Electrostatic Wager' },
} as const;
