// src/core/dbc/monk_spell_data.ts
/**
 * Monk DBC spell data — hand-authored from SpellDataDump/monk.txt.
 * Future: regenerated by scripts/generate-dbc-monk.ts
 */
import { SpellData } from './spell_data';

export const MONK_DBC: Record<number, SpellData> = {
  // Windwalker Monk passive (137025):
  // - effectN(1): -10% direct damage baseline for WW abilities
  // - effectN(2): -10% periodic damage baseline for WW abilities
  // - effectN(5): +245% auto-attack damage
  // - effectN(15): +188% direct damage for RSK/GotD/RWK family
  // - effectN(19): +25% direct damage for Jadefire Stomp labeled spells
  137025: new SpellData(137025, 'Windwalker Monk',
    [
      { _id: 179709, _subtype: 108, _value: -10, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 191100, _subtype: 108, _value: -10, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 0, _subtype: 0, _value: 0, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 0, _subtype: 0, _value: 0, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 191103, _subtype: 344, _value: 245, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 0, _subtype: 0, _value: 0, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 0, _subtype: 0, _value: 0, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 0, _subtype: 0, _value: 0, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 0, _subtype: 0, _value: 0, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 0, _subtype: 0, _value: 0, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 0, _subtype: 0, _value: 0, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 0, _subtype: 0, _value: 0, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 0, _subtype: 0, _value: 0, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 0, _subtype: 0, _value: 0, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 739777, _subtype: 108, _value: 188, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 984572, _subtype: 108, _value: -20, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 984590, _subtype: 108, _value: 90, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1266579, _subtype: 108, _value: 1647, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1286217, _subtype: 218, _value: 25, _ap_coefficient: 0, _sp_coefficient: 0 },
    ]),

  // Tiger Palm (100780): effectN(1) AP coeff = 0.9
  100780: new SpellData(100780, 'Tiger Palm',
    [{ _id: 108857, _subtype: 2, _value: 0, _ap_coefficient: 0.9, _sp_coefficient: 0 }],
    0, 1500),

  // Rising Sun Kick (107428): effectN(1) triggers rising_sun_kick_damage (185099).
  // DBC effect 268390 (effectN(1) of spell 185099): ap_coeff = 1.438.
  // Source: SimC sc_spell_data.inc effect entry for id 268390, field[11] = 1.438000.
  107428: new SpellData(107428, 'Rising Sun Kick',
    [{ _id: 185099, _subtype: 2, _value: 0, _ap_coefficient: 1.438, _sp_coefficient: 0 }],
    0, 1500),

  // Fists of Fury (113656): effectN(1) AP coeff = 2.6082 (per-tick, 5 ticks over 4s)
  113656: new SpellData(113656, 'Fists of Fury',
    [{ _id: 117418, _subtype: 2, _value: 0, _ap_coefficient: 2.6082, _sp_coefficient: 0 }],
    0, 1500),

  // Blackout Kick (100784): effectN(1) AP coeff = 0.847
  100784: new SpellData(100784, 'Blackout Kick',
    [{ _id: 228649, _subtype: 2, _value: 0, _ap_coefficient: 0.847, _sp_coefficient: 0 }],
    0, 1500),

  // Sharp Reflexes talent (261917): effectN(1) = -1s CD reduction per BoK
  261917: new SpellData(261917, 'Sharp Reflexes',
    [{ _id: 488021, _subtype: 4, _value: -1, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Combo Breaker talent (137384): effectN(1) = 8 (8% proc chance)
  137384: new SpellData(137384, 'Combo Breaker',
    [{ _id: 180339, _subtype: 4, _value: 8, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Rising Star talent (388849): effectN(1) = +15% direct damage,
  // effectN(2) = +12% crit bonus multiplier on RSK / GotD / RWK.
  // (Rank 1 curve adjusts eff#2 from base 10 → 12.)
  // Ref: SimC debug — "setting talent Rising Star rank 1 eff#2 value, old=10, new=12"
  388849: new SpellData(388849, 'Rising Star',
    [
      { _id: 1024787, _subtype: 108, _value: 15, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1054746, _subtype: 108, _value: 12, _ap_coefficient: 0, _sp_coefficient: 0 },
    ]),

  // Flurry Strikes talent (450615): 1 charge for 1H hits, 2 charges for 2H hits.
  450615: new SpellData(450615, 'Flurry Strikes',
    [
      { _id: 1150629, _subtype: 4, _value: 1, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1151332, _subtype: 4, _value: 2, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1167368, _subtype: 4, _value: 0, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1167369, _subtype: 4, _value: 0, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1167370, _subtype: 4, _value: 625, _ap_coefficient: 0, _sp_coefficient: 0 },
    ]),

  // One Versus Many (450988): crits double Flurry Charge generation.
  450988: new SpellData(450988, 'One Versus Many',
    [
      { _id: 1151270, _subtype: 4, _value: 1, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1151622, _subtype: 108, _value: 50, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1151623, _subtype: 108, _value: 35, _ap_coefficient: 0, _sp_coefficient: 0 },
    ]),

  // Celestial Conduit / Zenith (322101): effectN(3) = -1s extra CD reduction
  322101: new SpellData(322101, 'Celestial Conduit',
    [
      { _id: 0, _subtype: 0, _value: 0, _ap_coefficient: 0, _sp_coefficient: 0 }, // effectN(1)
      { _id: 0, _subtype: 0, _value: 0, _ap_coefficient: 0, _sp_coefficient: 0 }, // effectN(2)
      { _id: 0, _subtype: 4, _value: -1, _ap_coefficient: 0, _sp_coefficient: 0 }, // effectN(3)
    ]),

  // Improved Touch of Death (322113): execute threshold and % max-health damage branch.
  // effectN(1) = 15 (execute threshold), effectN(2) = 35 (% max HP damage).
  322113: new SpellData(322113, 'Improved Touch of Death',
    [
      { _id: 810254, _subtype: 4, _value: 15, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 810255, _subtype: 4, _value: 35, _ap_coefficient: 0, _sp_coefficient: 0 },
    ]),

  // Whirling Dragon Punch (152175): effectN(1) AP coeff — SimC uses normalized weapon, we use AP scaling
  // WDP in SimC hits 6 targets, but trainer models single-target; apCoeff derived from SimC data
  152175: new SpellData(152175, 'Whirling Dragon Punch',
    [{ _id: 158221, _subtype: 2, _value: 0, _ap_coefficient: 3.5, _sp_coefficient: 0 }],
    0, 1500),

  // Strike of the Windlord (392983): effectN(1) AP coeff
  392983: new SpellData(392983, 'Strike of the Windlord',
    [{ _id: 392984, _subtype: 2, _value: 0, _ap_coefficient: 5.25, _sp_coefficient: 0 }],
    0, 1500),

  // Thunderfist talent (392985): effectN(1) base_value = 4 (stacks granted per cast on first target).
  // Source: SimC SpellDataDump/monk.txt spell 392985 effect entry base_value field.
  392985: new SpellData(392985, 'Thunderfist',
    [{ _id: 1031605, _subtype: 4, _value: 4, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Thunderfist buff (393565): max 10 stacks, 60s duration. Triggers 393566 on melee hit.
  // Source: SimC SpellDataDump/monk.txt spell 393565, max_stack = 10, duration = 60s.
  393565: new SpellData(393565, 'Thunderfist',
    [{ _id: 1032620, _subtype: 42, _value: 0, _ap_coefficient: 0, _sp_coefficient: 0 }],
    0, 1500,
    { _max_stacks: 10, _duration_ms: 60_000 }),

  // Thunderfist proc damage (393566): Nature school, AP coefficient 1.61.
  // Source: SimC SpellDataDump/monk.txt spell 393566 effect entry ap_coefficient field.
  393566: new SpellData(393566, 'Thunderfist',
    [{ _id: 1032621, _subtype: 2, _value: 0, _ap_coefficient: 1.61, _sp_coefficient: 0 }],
    0, 0),

  // Xuen's Battlegear talent (392993): effectN(1) = +20% crit chance to
  // RSK / GotD / RWK, effectN(2) = 4000ms Fists of Fury cooldown reduction on crit.
  392993: new SpellData(392993, "Xuen's Battlegear",
    [
      { _id: 1031618, _subtype: 107, _value: 20, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1031619, _subtype: 4, _value: 4000, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1031620, _subtype: 4, _value: 40, _ap_coefficient: 0, _sp_coefficient: 0 },
    ]),

  // Martial Instincts (450427): +4% physical damage done (rank 2 curve-adjusted; base was 5).
  // Ref: SimC debug — "setting talent Martial Instincts rank 2 effect value, old=5, new=4"
  450427: new SpellData(450427, 'Martial Instincts',
    [{ _id: 1150320, _subtype: 79, _value: 4, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Chi Proficiency (450426): +4% magic damage done.
  450426: new SpellData(450426, 'Chi Proficiency',
    [{ _id: 1150315, _subtype: 79, _value: 4, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Spinning Crane Kick tick (107270): AP coeff = 0.1 per tick, 4 ticks over 1.5s
  // Source: SimC SpellDataDump/monk.txt, child spell of cast spell 101546
  101546: new SpellData(101546, 'Spinning Crane Kick',
    [{ _id: 107270, _subtype: 2, _value: 0, _ap_coefficient: 0.1, _sp_coefficient: 0 }],
    0, 1500),

  // Berserking (Troll racial): no damage, no AP coefficient
  26297: new SpellData(26297, 'Berserking',
    [{ _id: 0, _subtype: 0, _value: 0, _ap_coefficient: 0, _sp_coefficient: 0 }],
    0, 0),

  // Touch of Death (322109): execute spell, no AP coefficient — damage = player max HP
  322109: new SpellData(322109, 'Touch of Death',
    [{ _id: 0, _subtype: 0, _value: 0, _ap_coefficient: 0, _sp_coefficient: 0 }],
    0, 0),

  // Slicing Winds damage (1217411): AP coeff = 4.48, nature school
  // Source: SimC SpellDataDump/monk.txt, effect entry for damage spell 1217411
  1217411: new SpellData(1217411, 'Slicing Winds',
    [{ _id: 1217411, _subtype: 2, _value: 0, _ap_coefficient: 4.48, _sp_coefficient: 0 }],
    0, 1500),

  // Skyfire Heel talent (1248704):
  // effectN(1) = 10 → 10% of RSK damage splashes to nearby enemies
  // effectN(2) = 5 → AoE reduced targets
  // effectN(3) = 5 → max enemies for crit scaling
  1248704: new SpellData(1248704, 'Skyfire Heel',
    [
      { _id: 1251813, _subtype: 4, _value: 10, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1251814, _subtype: 4, _value: 5, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1251815, _subtype: 395, _value: 5, _ap_coefficient: 0, _sp_coefficient: 0 },
    ]),

  // Skyfire Heel buff (1248705):
  // effectN(1) = 4 → +4% crit chance per nearby enemy on RSK/RWK/GotD family
  1248705: new SpellData(1248705, 'Skyfire Heel',
    [{ _id: 1251816, _subtype: 107, _value: 4, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Pressure Point buff (337482): effectN(1) = +40% flat crit chance on RSK/GotD/RWK.
  337482: new SpellData(337482, 'Pressure Point',
    [{ _id: 835536, _subtype: 107, _value: 40, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Fast Feet (388809) — Windwalker/Mistweaver class talent:
  // effectN(1): +70% direct damage to RSK (107428, 185099), GotD (392959), RWK (467307, 468179).
  // effectN(2): +10% direct damage to SCK (101546, 107270, 322729).
  // Source: SpellDataDump/monk.txt lines 10789-10806, effect ids 1024727/1024728.
  388809: new SpellData(388809, 'Fast Feet',
    [
      { _id: 1024727, _subtype: 108, _value: 70, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1024728, _subtype: 108, _value: 10, _ap_coefficient: 0, _sp_coefficient: 0 },
    ]),

  // Sunfire Spiral (1272415): effectN(1) = 40 → RSK gains 40% additional mastery effectiveness.
  1272415: new SpellData(1272415, 'Sunfire Spiral',
    [{ _id: 1285642, _subtype: 4, _value: 40, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Energy Burst talent (451498): effectN(1) = 100% proc chance, effectN(2) = 1 chi.
  451498: new SpellData(451498, 'Energy Burst',
    [
      { _id: 1152128, _subtype: 4, _value: 100, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1152129, _subtype: 4, _value: 1, _ap_coefficient: 0, _sp_coefficient: 0 },
    ]),

  // Teachings of the Monastery (116645): effectN(1) = 12% RSK cooldown reset chance per BoK stack.
  116645: new SpellData(116645, 'Teachings of the Monastery',
    [{ _id: 131760, _subtype: 4, _value: 12, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Rushing Wind Kick talent (1250566): effectN(1) = 60% proc chance on free BoK.
  1250566: new SpellData(1250566, 'Rushing Wind Kick',
    [{ _id: 1254684, _subtype: 4, _value: 60, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Rushing Wind Kick cast spell (467307):
  // - effectN(1): trigger spell 468179, base_value 6 (used as +6% per target scalar)
  // - effectN(2): max targets for scalar (5)
  // Damage AP coefficient comes from trigger spell 468179 effect #1: 1.7975.
  // Source: SimC SpellDataDump/monk.txt (spells 467307 and 468179).
  467307: new SpellData(467307, 'Rushing Wind Kick',
    [
      { _id: 1180392, _subtype: 64, _value: 6, _ap_coefficient: 1.7975, _sp_coefficient: 0 },
      { _id: 1181690, _subtype: 3, _value: 5, _ap_coefficient: 0, _sp_coefficient: 0 },
    ],
    0, 1500),

  // Revolving Whirl (451524): effectN(1) = 100% → SotW/WDP proc Dance of Chi-Ji.
  451524: new SpellData(451524, 'Revolving Whirl',
    [{ _id: 1152168, _subtype: 4, _value: 100, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Dual Threat (451823): effectN(1) = 30% proc chance.
  451823: new SpellData(451823, 'Dual Threat',
    [{ _id: 1152583, _subtype: 4, _value: 30, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Harmonic Combo (1250041): effectN(1) = -1 chi, effectN(2) = -10% FoF damage.
  1250041: new SpellData(1250041, 'Harmonic Combo',
    [
      { _id: 1253953, _subtype: 107, _value: -1, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1253954, _subtype: 108, _value: -10, _ap_coefficient: 0, _sp_coefficient: 0 },
    ]),

  // Momentum Boost buff (451297): effectN(1) = +10% FoF damage per stack.
  451297: new SpellData(451297, 'Momentum Boost',
    [{ _id: 1151795, _subtype: 108, _value: 10, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Tigereye Brew FoF buff (1262042): effectN(1) = +15% FoF damage per stack.
  1262042: new SpellData(1262042, 'Tigereye Brew',
    [{ _id: 1272065, _subtype: 108, _value: 15, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Touch of the Tiger (388856): effectN(1) = +50% Tiger Palm direct damage.
  388856: new SpellData(388856, 'Touch of the Tiger',
    [{ _id: 1024796, _subtype: 108, _value: 50, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Memory of the Monastery (454969): effectN(1) = +75% CB proc modifier, effectN(2) = +30% TP damage.
  454969: new SpellData(454969, 'Memory of the Monastery',
    [
      { _id: 1157993, _subtype: 218, _value: 75, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1250509, _subtype: 108, _value: 30, _ap_coefficient: 0, _sp_coefficient: 0 },
    ]),

  // Efficient Training (450989): effectN(1) = +20% direct damage (doubled by WW passive 1258122 #16).
  450989: new SpellData(450989, 'Efficient Training',
    [
      { _id: 1151271, _subtype: 108, _value: 20, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1151635, _subtype: 108, _value: 20, _ap_coefficient: 0, _sp_coefficient: 0 },
    ]),

  // Knowledge of the Broken Temple (451529): effectN(1) = 4 TotM stacks, effectN(2) = +20% WDP/SotW damage.
  451529: new SpellData(451529, 'Knowledge of the Broken Temple',
    [
      { _id: 1152176, _subtype: 4, _value: 4, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1152177, _subtype: 108, _value: 20, _ap_coefficient: 0, _sp_coefficient: 0 },
    ]),

  // Communion With Wind (451576): effectN(1) = -5000ms CD, effectN(2) = +20% WDP/SotW damage.
  451576: new SpellData(451576, 'Communion With Wind',
    [
      { _id: 1152266, _subtype: 107, _value: -5000, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1152267, _subtype: 108, _value: 20, _ap_coefficient: 0, _sp_coefficient: 0 },
    ]),

  // Midnight Season 2pc (1264842): effectN(1) = +30% WDP/SotW damage.
  1264842: new SpellData(1264842, 'Monk Windwalker12.0 Class Set 2pc',
    [{ _id: 1276449, _subtype: 108, _value: 30, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Weapons of the Wall (1262610): effectN(1) = +20% Zenith Stomp damage, effectN(2) = +20% Stomp damage.
  1262610: new SpellData(1262610, 'Weapons of the Wall',
    [
      { _id: 1272983, _subtype: 218, _value: 20, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1272984, _subtype: 218, _value: 20, _ap_coefficient: 0, _sp_coefficient: 0 },
    ]),

  // Stand Ready (1262603): effectN(1) = +10 Flurry Strikes, effectN(2) = 70% effectiveness.
  1262603: new SpellData(1262603, 'Stand Ready',
    [
      { _id: 1272970, _subtype: 4, _value: 10, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1272971, _subtype: 4, _value: 70, _ap_coefficient: 0, _sp_coefficient: 0 },
    ]),

  // Weapon of Wind (1272678): effectN(1) = +10% during Zenith (modifier to Zenith effects).
  1272678: new SpellData(1272678, 'Weapon of Wind',
    [
      { _id: 1285925, _subtype: 107, _value: 10, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1285926, _subtype: 107, _value: 10, _ap_coefficient: 0, _sp_coefficient: 0 },
    ]),

  // Tiger Fang (1272781): effectN(1) = +15% auto-attack crit, effectN(2) = +15% Dual Threat crit.
  1272781: new SpellData(1272781, 'Tiger Fang',
    [
      { _id: 1286072, _subtype: 334, _value: 15, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1286073, _subtype: 219, _value: 15, _ap_coefficient: 0, _sp_coefficient: 0 },
    ]),

  // Wisdom of the Wall (1272821): effectN(1) = 3 flurry strikes, internal cooldown = 1s.
  1272821: new SpellData(1272821, 'Wisdom of the Wall',
    [{ _id: 1286132, _subtype: 4, _value: 3, _ap_coefficient: 0, _sp_coefficient: 0 }],
    0, 1500,
    { _internal_cooldown_ms: 1_000 }),

  // Ferocity of Xuen (388674): effectN(1) = +2% all damage per rank (max 2 ranks → 4%).
  388674: new SpellData(388674, 'Ferocity of Xuen',
    [{ _id: 1024507, _subtype: 79, _value: 2, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Ferociousness (458623): effectN(1) = +2% crit chance per rank (rank 2 = 4%).
  458623: new SpellData(458623, 'Ferociousness',
    [{ _id: 1164724, _subtype: 290, _value: 2, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Skyfury (462854): external raid buff auto-attack repeat driver.
  // Source: SimC SpellDataDump/shaman.txt (proc chance 20%, internal cooldown 0.1s).
  462854: new SpellData(462854, 'Skyfury',
    [
      { _id: 1173055, _subtype: 318, _value: 2, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1286687, _subtype: 0, _value: 0, _ap_coefficient: 0, _sp_coefficient: 0 },
    ],
    0, 1500,
    { _proc_chance_pct: 20, _internal_cooldown_ms: 100, _duration_ms: 3_600_000 }),

  // Hit Combo buff (196741): effectN(1) = +1% damage per stack.
  196741: new SpellData(196741, 'Hit Combo',
    [{ _id: 288843, _subtype: 108, _value: 1, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Vigilant Watch (450993): effectN(1) = +30% crit bonus multiplier on BoK.
  450993: new SpellData(450993, 'Vigilant Watch',
    [{ _id: 1151275, _subtype: 108, _value: 30, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Mystic Touch debuff (113746): effectN(1) = +5% physical damage taken.
  113746: new SpellData(113746, 'Mystic Touch',
    [{ _id: 126739, _subtype: 87, _value: 5, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Tigereye Brew crit buff (1261724): effectN(1) = +2% crit per stack during Zenith.
  1261724: new SpellData(1261724, 'Tigereye Brew',
    [{ _id: 1271571, _subtype: 4, _value: 2, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Tigereye Brew crit bonus multiplier talent (1261844): effectN(1) subtype 108 (Add Percent Modifier)
  // on Spell Critical Bonus Multiplier (15). Base value 5, talent rank overrides [op=set, values=(10, 20)].
  // Rank 1 → 10%, rank 2 → 20%. Applied to crit_bonus_multiplier in SimC's parse_effects.
  1261844: new SpellData(1261844, 'Tigereye Brew',
    [{ _id: 1271720, _subtype: 108, _value: 10, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Momentum Boost speed buff (451298): effectN(1) = +60% auto attack speed.
  451298: new SpellData(451298, 'Momentum Boost',
    [{ _id: 1151798, _subtype: 342, _value: 60, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Pride of Pandaria (450979): effectN(1) = +15% crit chance to Flurry Strike (450617, 451250).
  // Source: SimC SpellDataDump/monk.txt spell 450979, subtype 107 (Apply Flat Modifier w/ Label: Spell Critical Chance).
  450979: new SpellData(450979, 'Pride of Pandaria',
    [{ _id: 1151279, _subtype: 107, _value: 15, _ap_coefficient: 0, _sp_coefficient: 0 }]),

  // Jade Ignition (392979): effectN(1) = 40 (chi energy stacks), effectN(2) = 30 (max stacks),
  // effectN(3) = 5 (reduced beyond targets).
  392979: new SpellData(392979, 'Jade Ignition',
    [
      { _id: 1031594, _subtype: 42, _value: 40, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1031595, _subtype: 4, _value: 30, _ap_coefficient: 0, _sp_coefficient: 0 },
      { _id: 1164132, _subtype: 4, _value: 5, _ap_coefficient: 0, _sp_coefficient: 0 },
    ]),
};

/** Look up a spell by ID. Returns undefined if not in DB. */
export function getMonkSpell(id: number): SpellData | undefined {
  return MONK_DBC[id];
}

/**
 * Returns required monk DBC spell data and fails loudly when a hardcoded entry is missing.
 */
export function requireMonkSpellData(spellId: number): SpellData {
  const spell = MONK_DBC[spellId];
  if (!spell) {
    throw new Error(`Missing MONK_DBC entry for spell ${spellId}`);
  }
  return spell;
}

